export const styles = {
  app: {
    minHeight: '100vh',
    backgroundColor: '#F5F5F5',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    paddingBottom: '70px',
  },
  main: {
    maxWidth: '600px',
    margin: '0 auto',
    backgroundColor: '#fff',
    minHeight: '100vh',
  },
  page: {
    padding: '16px',
    paddingBottom: '20px',
  },
  header: {
    marginBottom: '20px',
  },
  headerTitle: {
    fontSize: '24px',
    fontWeight: '700',
    margin: '0 0 4px 0',
    color: '#212121',
  },
  headerSubtitle: {
    fontSize: '14px',
    color: '#666',
    margin: 0,
  },
  bottomNav: {
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    maxWidth: '600px',
    width: '100%',
    height: '70px',
    backgroundColor: '#fff',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTop: '1px solid #E0E0E0',
    boxShadow: '0 -2px 10px rgba(0,0,0,0.05)',
    zIndex: 1000,
  },
  navButton: {
    background: 'none',
    border: 'none',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    padding: '8px 12px',
    transition: 'color 0.3s',
  },
  navLabel: {
    fontSize: '11px',
    fontWeight: '500',
  },
  balanceCard: {
    background: 'linear-gradient(135deg, #4CAF50 0%, #45a049 100%)',
    borderRadius: '16px',
    padding: '24px',
    color: '#fff',
    marginBottom: '20px',
    boxShadow: '0 4px 12px rgba(76, 175, 80, 0.3)',
  },
  balanceLabel: {
    fontSize: '14px',
    opacity: 0.9,
    margin: '0 0 8px 0',
  },
  balanceAmount: {
    fontSize: '32px',
    fontWeight: '700',
    margin: '0 0 20px 0',
  },
  balanceStats: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  statLabel: {
    fontSize: '12px',
    opacity: 0.9,
    margin: '0 0 4px 0',
  },
  statValue: {
    fontSize: '16px',
    fontWeight: '600',
    margin: 0,
  },
  quickActions: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    marginBottom: '24px',
  },
  quickActionBtn: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    color: '#4CAF50',
    transition: 'all 0.3s',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
  },
  section: {
    marginBottom: '24px',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: '600',
    margin: 0,
    color: '#212121',
  },
  goalCard: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '16px',
    marginBottom: '12px',
  },
  goalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  goalTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#212121',
  },
  goalAmount: {
    fontSize: '14px',
    color: '#4CAF50',
    fontWeight: '600',
  },
  progressBar: {
    width: '100%',
    height: '8px',
    backgroundColor: '#E0E0E0',
    borderRadius: '4px',
    overflow: 'hidden',
    position: 'relative',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4CAF50',
    borderRadius: '4px',
    transition: 'width 0.3s',
  },
  transactionItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px',
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    marginBottom: '8px',
  },
  transactionIcon: {
    fontSize: '24px',
  },
  transactionInfo: {
    flex: 1,
  },
  transactionCategory: {
    fontSize: '14px',
    fontWeight: '600',
    margin: '0 0 4px 0',
    color: '#212121',
  },
  transactionDate: {
    fontSize: '12px',
    color: '#666',
    margin: 0,
  },
  transactionAmount: {
    fontSize: '14px',
    fontWeight: '600',
  },
  aiTip: {
    backgroundColor: '#E8F5E9',
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
  },
  aiTipTitle: {
    fontSize: '14px',
    fontWeight: '600',
    margin: '0 0 8px 0',
    color: '#212121',
  },
  aiTipText: {
    fontSize: '13px',
    color: '#666',
    margin: 0,
    lineHeight: '1.5',
  },
  tabNav: {
    display: 'flex',
    gap: '8px',
    marginBottom: '20px',
    borderBottom: '1px solid #E0E0E0',
    paddingBottom: '8px',
  },
  tabButton: {
    flex: 1,
    padding: '10px',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '500',
    color: '#666',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  tabButtonActive: {
    backgroundColor: '#4CAF50',
    color: '#fff',
  },
  addButton: {
    width: '100%',
    padding: '14px',
    backgroundColor: '#4CAF50',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    marginBottom: '16px',
    boxShadow: '0 2px 8px rgba(76, 175, 80, 0.3)',
  },
  expenseItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '16px',
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    marginBottom: '8px',
  },
  expenseLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  expenseCategory: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#212121',
  },
  expenseNote: {
    fontSize: '13px',
    color: '#666',
  },
  expenseDate: {
    fontSize: '12px',
    color: '#999',
  },
  expenseAmount: {
    fontSize: '16px',
    fontWeight: '600',
  },
  goalCardLarge: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '16px',
  },
  goalStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '12px',
  },
  goalStatusText: {
    fontSize: '13px',
    fontWeight: '600',
  },
  goalCardTitle: {
    fontSize: '18px',
    fontWeight: '600',
    margin: '0 0 16px 0',
    color: '#212121',
  },
  goalProgress: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '12px',
  },
  goalPercent: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#4CAF50',
    minWidth: '50px',
    textAlign: 'right',
  },
  goalDetails: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    color: '#666',
  },
  chartCard: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '16px',
  },
  chartTitle: {
    fontSize: '16px',
    fontWeight: '600',
    margin: '0 0 16px 0',
    color: '#212121',
  },
  progressCard: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '20px',
  },
  progressLabel: {
    fontSize: '14px',
    color: '#666',
    margin: '0 0 16px 0',
  },
  progressStats: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '16px',
    textAlign: 'center',
  },
  progressNumber: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#4CAF50',
    margin: '0 0 4px 0',
  },
  progressText: {
    fontSize: '12px',
    color: '#666',
    margin: 0,
  },
  lessonCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    marginBottom: '12px',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  lessonBadge: {
    fontSize: '32px',
  },
  lessonContent: {
    flex: 1,
  },
  lessonTitle: {
    fontSize: '16px',
    fontWeight: '600',
    margin: '0 0 8px 0',
    color: '#212121',
  },
  lessonProgress: {
    fontSize: '13px',
    color: '#666',
    margin: '0 0 8px 0',
  },
  quizCard: {
    backgroundColor: '#FFF3E0',
    border: '2px solid #FFB74D',
    borderRadius: '12px',
    padding: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  quizTitle: {
    fontSize: '16px',
    fontWeight: '600',
    margin: '0 0 4px 0',
    color: '#212121',
  },
  quizText: {
    fontSize: '13px',
    color: '#666',
    margin: 0,
  },
  quizButton: {
    padding: '10px 20px',
    backgroundColor: '#FFB74D',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  statsCard: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '12px',
    marginBottom: '24px',
  },
  statBox: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    textAlign: 'center',
  },
  challengeCard: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '16px',
    marginBottom: '12px',
  },
  challengeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  challengeTitle: {
    fontSize: '14px',
    fontWeight: '600',
    margin: 0,
    color: '#212121',
  },
  challengeReward: {
    fontSize: '13px',
    color: '#4CAF50',
    fontWeight: '600',
  },
  challengeProgress: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '8px',
  },
  challengeText: {
    fontSize: '13px',
    color: '#666',
    minWidth: '40px',
    textAlign: 'right',
  },
  challengeType: {
    fontSize: '12px',
    color: '#999',
  },
  leaderboardItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px',
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    marginBottom: '8px',
  },
  leaderboardItemMe: {
    backgroundColor: '#E8F5E9',
    border: '2px solid #4CAF50',
  },
  leaderboardLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  leaderboardRank: {
    fontSize: '16px',
    fontWeight: '700',
    minWidth: '30px',
  },
  leaderboardAvatar: {
    fontSize: '24px',
  },
  leaderboardName: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#212121',
  },
  leaderboardPoints: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#4CAF50',
  },
  profileCard: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '24px',
    textAlign: 'center',
    marginBottom: '24px',
  },
  profileAvatar: {
    fontSize: '64px',
    marginBottom: '12px',
  },
  profileName: {
    fontSize: '20px',
    fontWeight: '700',
    margin: '0 0 8px 0',
    color: '#212121',
  },
  profileLevel: {
    fontSize: '14px',
    color: '#666',
    margin: 0,
  },
  aiCard: {
    backgroundColor: '#E8F5E9',
    borderLeft: '4px solid #4CAF50',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '12px',
  },
  aiCardTitle: {
    fontSize: '14px',
    fontWeight: '600',
    margin: '0 0 8px 0',
    color: '#212121',
  },
  aiCardText: {
    fontSize: '13px',
    color: '#666',
    margin: 0,
    lineHeight: '1.5',
  },
  menuItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px',
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    marginBottom: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  menuLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  menuIcon: {
    fontSize: '20px',
  },
  menuLabel: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#212121',
  },
  logoutButton: {
    width: '100%',
    padding: '14px',
    backgroundColor: '#F44336',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '20px',
  },
  infoCard: {
    backgroundColor: '#fff',
    border: '1px solid #E0E0E0',
    borderRadius: '12px',
    padding: '16px',
  },
  infoRow: {
    display: 'flex',
    padding: '12px 0',
    borderBottom: '1px solid #F5F5F5',
    gap: '12px',
  },
  infoLabel: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#666',
    minWidth: '120px',
  },
  infoValue: {
    fontSize: '14px',
    color: '#212121',
    flex: 1,
  },
  authWrapper: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    padding: '32px',
  },
  authCard: {
    width: '100%',
    maxWidth: '420px',
    backgroundColor: '#fff',
    borderRadius: '16px',
    padding: '32px',
    boxShadow: '0 12px 40px rgba(0,0,0,0.08)',
  },
  authTitle: {
    fontSize: '28px',
    fontWeight: '700',
    margin: '0 0 12px 0',
    color: '#212121',
  },
  authSubtitle: {
    fontSize: '14px',
    color: '#616161',
    lineHeight: '1.6',
    margin: '0 0 24px 0',
  },
  authForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    marginTop: '8px',
  },
  authField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  authDoubleField: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  authLabel: {
    fontSize: '13px',
    color: '#616161',
    fontWeight: '600',
  },
  authInput: {
    width: '100%',
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid #E0E0E0',
    fontSize: '14px',
    transition: 'border-color 0.2s, box-shadow 0.2s',
    outline: 'none',
  },
  authHint: {
    fontSize: '12px',
    color: '#9E9E9E',
    margin: '4px 0 0 0',
  },
  authButton: {
    width: '100%',
    padding: '14px',
    borderRadius: '12px',
    border: 'none',
    backgroundColor: '#4CAF50',
    color: '#fff',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '8px',
    boxShadow: '0 8px 20px rgba(76, 175, 80, 0.3)',
  },
  authBypassButton: {
    width: '100%',
    padding: '12px',
    borderRadius: '12px',
    border: '1px dashed #9E9E9E',
    backgroundColor: '#FAFAFA',
    color: '#424242',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '16px',
  },
  authFooter: {
    marginTop: '20px',
    fontSize: '13px',
    color: '#757575',
    textAlign: 'center',
  },
  authLink: {
    color: '#4CAF50',
    fontWeight: '600',
    textDecoration: 'none',
  },
  authLinkInline: {
    color: '#4CAF50',
    fontWeight: '600',
    textDecoration: 'none',
  },
  authNotice: {
    backgroundColor: '#E8F5E9',
    borderRadius: '10px',
    padding: '12px 16px',
    fontSize: '13px',
    color: '#2E7D32',
    marginBottom: '16px',
  },
  authError: {
    backgroundColor: '#FFEBEE',
    borderRadius: '10px',
    padding: '12px 16px',
    fontSize: '13px',
    color: '#C62828',
    marginBottom: '16px',
  },
};

export default styles;

